# .github/workflows/delete-branch-on-done.yml
name: Delete Git branch when Jira issue is Done

on:
  repository_dispatch:
    types: [jira-issue-done]

jobs:
  delete-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Set up environment
        env:
          ISSUE_KEY: ${{ github.event.client_payload.issueKey }}
        run: |
          echo "Received Jira issue key: $ISSUE_KEY"

      - name: Get matching branches
        env:
          ISSUE_KEY: ${{ github.event.client_payload.issueKey }}
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          echo "Fetching branches containing: $ISSUE_KEY"
          BRANCHES=$(curl -s -H "Authorization: token $GH_TOKEN" \
            https://api.github.com/repos/$REPO/branches \
            | jq -r '.[].name' | grep "$ISSUE_KEY" || true)

          if [ -z "$BRANCHES" ]; then
            echo "✅ No matching branches found for $ISSUE_KEY"
            exit 0
          fi

          for BRANCH in $BRANCHES; do
            echo "🗑️ Deleting branch: $BRANCH"
            curl -X DELETE -H "Authorization: token $GH_TOKEN" \
              https://api.github.com/repos/$REPO/git/refs/heads/$BRANCH
          done
