name: Auto Delete Branch After PR Closed

on:
  pull_request:
    types: [closed]

jobs:
  delete-branch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Delete branch if not main/master
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
          REPO_NAME: ${{ github.repository }}
        run: |
          echo "Branch to delete: $BRANCH_NAME"

          # Không xóa nếu là nhánh chính
          if [[ "$BRANCH_NAME" == "main" || "$BRANCH_NAME" == "master" ]]; then
            echo "⚠️ Not deleting branch $BRANCH_NAME (main/master)"
            exit 0
          fi

          # Gọi GitHub API để xóa nhánh
          curl -X DELETE \
            -H "Authorization: token $GH_TOKEN" \
            https://api.github.com/repos/$REPO_NAME/git/refs/heads/$BRANCH_NAME
