name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # Hoặc nhánh chính của bạn

jobs:
  build:
    runs-on: ubuntu-latest  # Dùng môi trường Ubuntu để chạy CI

    steps:
    # 1. Checkout mã nguồn
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Thiết lập JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # 3. Build WAR file từ mã nguồn (nếu có sử dụng Maven hoặc Gradle)
    - name: Build WAR with Maven
      run: mvn clean package

    # 4. Đăng nhập vào Docker Hub
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # 5. Build Docker Image
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/springmvc-app:${{ github.sha }} -t ${{ secrets.DOCKER_USERNAME }}/springmvc-app:latest .

    # 6. Push Docker Image lên Docker Hub
    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/springmvc-app:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USERNAME }}/springmvc-app:latest
