name: Build & Push Docker Image

on:
  push:
    branches:
      - master  # Đảm bảo sử dụng nhánh chính chính xác

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build WAR with Maven
      run: mvn clean package

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/springmvc-app:${{ github.sha }} -t ${{ secrets.DOCKER_USERNAME }}/springmvc-app:latest .

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/springmvc-app:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USERNAME }}/springmvc-app:latest
